import 'package:flutter/material.dart';
import 'api_client.dart';
import 'models.dart';

void main() => runApp(const NikSpeedApp());
const green=Color(0xff1d2b24), terracotta=Color(0xffc7613c), cream=Color(0xfffbfaf7);
String ugx(int value)=>value.toString().replaceAllMapped(RegExp(r'(?=(\d{3})+(?!\d))'), (_) => ',');

class NikSpeedApp extends StatefulWidget { const NikSpeedApp({super.key}); @override State<NikSpeedApp> createState()=>_NikSpeedAppState(); }
class _NikSpeedAppState extends State<NikSpeedApp> { final api=ApiClient(); String? token,name,email; final Set<String> saved={}; void login(Map<String,dynamic> data){setState((){token=data['token'];name=data['name'];email=data['email'];});} @override Widget build(BuildContext context)=>MaterialApp(title:'Nik-Speed Properties',theme:ThemeData(useMaterial3:true,colorScheme:ColorScheme.fromSeed(seedColor:terracotta,primary:terracotta,surface:cream),scaffoldBackgroundColor:cream,appBarTheme:const AppBarTheme(backgroundColor:cream,foregroundColor:green,elevation:0)),home:HomeScreen(app:this)); }

class HomeScreen extends StatefulWidget { const HomeScreen({super.key,required this.app}); final _NikSpeedAppState app; @override State<HomeScreen> createState()=>_HomeScreenState(); }
class _HomeScreenState extends State<HomeScreen>{int index=0; @override Widget build(BuildContext context){final pages=[DiscoverPage(app:widget.app),SavedPage(app:widget.app),AdvertisePage(app:widget.app)];return Scaffold(appBar:AppBar(title:const Text('nik speed',style:TextStyle(fontWeight:FontWeight.w800,fontSize:24)),actions:[IconButton(icon:const Icon(Icons.account_circle_outlined),onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>AccountPage(app:widget.app))) )]),body:pages[index],bottomNavigationBar:NavigationBar(selectedIndex:index,onDestinationSelected:(value)=>setState(()=>index=value),destinations:const[NavigationDestination(icon:Icon(Icons.search),label:'Discover'),NavigationDestination(icon:Icon(Icons.favorite_border),label:'Saved'),NavigationDestination(icon:Icon(Icons.campaign_outlined),label:'Advertise')]));}}

class DiscoverPage extends StatefulWidget { const DiscoverPage({super.key,required this.app}); final _NikSpeedAppState app; @override State<DiscoverPage> createState()=>_DiscoverPageState(); }
class _DiscoverPageState extends State<DiscoverPage>{late Future<List<Property>> future; final location=TextEditingController();String type='';@override void initState(){super.initState();future=widget.app.api.properties();}void search()=>setState(()=>future=widget.app.api.properties(type:type,location:location.text));@override Widget build(BuildContext context)=>FutureBuilder<List<Property>>(future:future,builder:(context,snapshot)=>ListView(padding:const EdgeInsets.all(20),children:[const Text('Find a place that\nfeels like home.',style:TextStyle(fontSize:32,fontWeight:FontWeight.w800,color:green)),const SizedBox(height:10),const Text('Homes for sale, apartments for rent and land across Uganda.'),const SizedBox(height:22),Row(children:[Expanded(child:DropdownButtonFormField(value:type,items:const[DropdownMenuItem(value:'',child:Text('All types')),DropdownMenuItem(value:'House for sale',child:Text('Houses for sale')),DropdownMenuItem(value:'Apartment for rent',child:Text('Apartments for rent')),DropdownMenuItem(value:'Land',child:Text('Land'))],onChanged:(value)=>setState(()=>type=value??''))),const SizedBox(width:10),IconButton.filled(icon:const Icon(Icons.tune),onPressed:search)]),const SizedBox(height:10),TextField(controller:location,decoration:InputDecoration(hintText:'Search location',suffixIcon:IconButton(icon:const Icon(Icons.search),onPressed:search))),const SizedBox(height:24),Text('Featured properties',style:Theme.of(context).textTheme.headlineSmall),const SizedBox(height:12),if(snapshot.hasError)ErrorPanel(message:'Could not load listings. Check the API connection.') else if(!snapshot.hasData)const Center(child:Padding(padding:EdgeInsets.all(40),child:CircularProgressIndicator())) else ...snapshot.data!.map((property)=>PropertyCard(property:property,app:widget.app))]));}

class PropertyCard extends StatelessWidget { const PropertyCard({super.key,required this.property,required this.app}); final Property property;final _NikSpeedAppState app;@override Widget build(BuildContext context){final saved=app.saved.contains(property.id);return Card(clipBehavior:Clip.antiAlias,margin:const EdgeInsets.only(bottom:16),child:InkWell(onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>PropertyPage(property:property,app:app))),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[SizedBox(height:180,width:double.infinity,child:Image.network(property.imageUrl,fit:BoxFit.cover,errorBuilder:(_,__,___)=>const ColoredBox(color:Color(0xffdde3dc))),),Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(property.type.toUpperCase(),style:const TextStyle(color:terracotta,fontSize:12,fontWeight:FontWeight.bold))),IconButton(icon:Icon(saved?Icons.favorite:Icons.favorite_border,color:terracotta),onPressed:(){app.setState(()=>saved?app.saved.remove(property.id):app.saved.add(property.id));})]),Text(property.title,style:const TextStyle(fontSize:20,fontWeight:FontWeight.bold)),const SizedBox(height:5),Text('⌖ ${property.location}',style:const TextStyle(color:Colors.blueGrey)),const SizedBox(height:12),Text('${property.currency} ${ugx(property.price)}',style:const TextStyle(fontWeight:FontWeight.bold,fontSize:17)),Text(property.bedrooms>0?'${property.bedrooms} beds · ${property.bathrooms} baths · ${property.area} ${property.areaUnit}':'${property.area} ${property.areaUnit}')])])])));}}

class SavedPage extends StatelessWidget { const SavedPage({super.key,required this.app});final _NikSpeedAppState app;@override Widget build(BuildContext context)=>FutureBuilder<List<Property>>(future:app.api.properties(),builder:(context,snapshot){final items=snapshot.data?.where((item)=>app.saved.contains(item.id)).toList()??[];return ListView(padding:const EdgeInsets.all(20),children:[const Text('Saved homes',style:TextStyle(fontSize:30,fontWeight:FontWeight.w800)),const SizedBox(height:10),if(items.isEmpty)const Padding(padding:EdgeInsets.only(top:40),child:Text('Tap the heart on a property to save it for later.')),...items.map((item)=>PropertyCard(property:item,app:app))]);});}

class PropertyPage extends StatelessWidget { const PropertyPage({super.key,required this.property,required this.app});final Property property;final _NikSpeedAppState app;@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(),body:ListView(children:[SizedBox(height:280,child:Image.network(property.imageUrl,width:double.infinity,fit:BoxFit.cover)),Padding(padding:const EdgeInsets.all(22),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(property.type.toUpperCase(),style:const TextStyle(color:terracotta,fontWeight:FontWeight.bold)),const SizedBox(height:8),Text(property.title,style:const TextStyle(fontSize:30,fontWeight:FontWeight.w800)),Text('⌖ ${property.location}'),const SizedBox(height:20),Text('${property.currency} ${ugx(property.price)}',style:const TextStyle(fontSize:24,fontWeight:FontWeight.w800)),const SizedBox(height:15),Wrap(spacing:12,children:[Chip(label:Text(property.bedrooms>0?'${property.bedrooms} beds':'Land')),Chip(label:Text('${property.bathrooms} baths')),Chip(label:Text('${property.area} ${property.areaUnit}'))]),const SizedBox(height:22),const Text('About this property',style:TextStyle(fontSize:21,fontWeight:FontWeight.bold)),Text(property.description),const SizedBox(height:24),FilledButton.icon(onPressed:()=>showModalBottomSheet(context:context,isScrollControlled:true,builder:(_)=>EnquirySheet(property:property,app:app)),icon:const Icon(Icons.mail_outline),label:Text('Contact ${property.agentName}'))]))]));}

class EnquirySheet extends StatefulWidget { const EnquirySheet({super.key,required this.property,required this.app});final Property property;final _NikSpeedAppState app;@override State<EnquirySheet> createState()=>_EnquirySheetState();}class _EnquirySheetState extends State<EnquirySheet>{final form=GlobalKey<FormState>();final name=TextEditingController(),email=TextEditingController(),phone=TextEditingController(),message=TextEditingController();bool loading=false;Future<void> send()async{if(!form.currentState!.validate())return;setState(()=>loading=true);try{await widget.app.api.enquire(widget.property,{'name':name.text,'email':email.text,'phone':phone.text,'message':message.text});if(mounted){Navigator.pop(context);ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Enquiry sent to the advertiser.')));}}on ApiException catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.message)));}finally{if(mounted)setState(()=>loading=false);}}@override Widget build(BuildContext context)=>Padding(padding:EdgeInsets.fromLTRB(24,24,24,24+MediaQuery.of(context).viewInsets.bottom),child:Form(key:form,child:Column(mainAxisSize:MainAxisSize.min,children:[Text('Contact ${widget.property.agentName}',style:const TextStyle(fontSize:22,fontWeight:FontWeight.bold)),TextFormField(controller:name,decoration:const InputDecoration(labelText:'Your name'),validator:(v)=>v!.isEmpty?'Required':null),TextFormField(controller:email,decoration:const InputDecoration(labelText:'Email'),validator:(v)=>v!.contains('@')?null:'Enter a valid email'),TextField(controller:phone,decoration:const InputDecoration(labelText:'Phone number')),TextField(controller:message,decoration:const InputDecoration(labelText:'Message'),maxLines:2),const SizedBox(height:18),FilledButton(onPressed:loading?null:send,child:Text(loading?'Sending…':'Send enquiry'))])));}

class AdvertisePage extends StatefulWidget { const AdvertisePage({super.key,required this.app});final _NikSpeedAppState app;@override State<AdvertisePage> createState()=>_AdvertisePageState();}class _AdvertisePageState extends State<AdvertisePage>{late Future<List<ListingPlan>> plans;@override void initState(){super.initState();plans=widget.app.api.plans();}@override Widget build(BuildContext context)=>ListView(padding:const EdgeInsets.all(20),children:[const Text('Advertise your property',style:TextStyle(fontSize:30,fontWeight:FontWeight.w800)),const SizedBox(height:8),const Text('Reach qualified buyers and tenants through a simple paid listing package.'),const SizedBox(height:22),FutureBuilder<List<ListingPlan>>(future:plans,builder:(context,snapshot){if(!snapshot.hasData)return const Center(child:Padding(padding:EdgeInsets.all(30),child:CircularProgressIndicator()));return Column(children:snapshot.data!.map((plan)=>Card(child:Padding(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(plan.name,style:const TextStyle(fontSize:21,fontWeight:FontWeight.bold)),Text('UGX ${ugx(plan.price)}',style:const TextStyle(fontSize:26,fontWeight:FontWeight.w800,color:terracotta)),Text('${plan.listings} listing credits · 30 days${plan.featured?' · Featured placement':''}'),const SizedBox(height:12),FilledButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>AccountPage(app:widget.app,selectedPlan:plan))),child:const Text('Choose package'))]))).toList());})]);}

class AccountPage extends StatefulWidget { const AccountPage({super.key,required this.app,this.selectedPlan});final _NikSpeedAppState app;final ListingPlan? selectedPlan;@override State<AccountPage> createState()=>_AccountPageState();}class _AccountPageState extends State<AccountPage>{bool registering=false,loading=false;final name=TextEditingController(),email=TextEditingController(),password=TextEditingController();Future<void> auth()async{setState(()=>loading=true);try{final result=await widget.app.api.authenticate(register:registering,name:name.text,email:email.text,password:password.text);widget.app.login(result);if(mounted)Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>DashboardPage(app:widget.app,selectedPlan:widget.selectedPlan)));}on ApiException catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.message)));}finally{if(mounted)setState(()=>loading=false);}}@override Widget build(BuildContext context){if(widget.app.token!=null)return DashboardPage(app:widget.app,selectedPlan:widget.selectedPlan);return Scaffold(appBar:AppBar(title:const Text('Advertiser account')),body:Padding(padding:const EdgeInsets.all(24),child:Column(children:[Text(registering?'Create your account':'Welcome back',style:const TextStyle(fontSize:28,fontWeight:FontWeight.w800)),if(registering)TextField(controller:name,decoration:const InputDecoration(labelText:'Name or agency')),TextField(controller:email,decoration:const InputDecoration(labelText:'Business email')),TextField(controller:password,obscureText:true,decoration:const InputDecoration(labelText:'Password (8+ characters)')),const SizedBox(height:20),FilledButton(onPressed:loading?null:auth,child:Text(loading?'Please wait…':registering?'Create account':'Sign in')),TextButton(onPressed:()=>setState(()=>registering=!registering),child:Text(registering?'Already registered? Sign in':'New advertiser? Create account'))])));}}
