"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { SiteShell } from "../components/SiteShell";
import { LocationLink } from "../components/LocationMap";

type Property = { id: string; title: string; type: string; location: string; price: number; currency: string; bedrooms: number; bathrooms: number; area: number; areaUnit: string; imageUrl: string; featured: boolean; description: string; agentName: string; agentPhone: string };
type Plan = { id: string; name: string; price: number; listings: number; featured: boolean };

const api = "";
const money = (price: number) => new Intl.NumberFormat("en-UG", { maximumFractionDigits: 0 }).format(price);
const fallback: Property[] = [
  { id: "1", title: "Modern villa with Lake Victoria views", type: "House for sale", location: "Entebbe, Wakiso", price: 850000000, currency: "UGX", bedrooms: 5, bathrooms: 4, area: 450, areaUnit: "sqm", imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85", featured: true, description: "A light-filled family home in a peaceful, secure estate.", agentName: "Sarah Namusoke", agentPhone: "+256 700 123 456" },
  { id: "2", title: "Serviced two-bedroom apartment", type: "Apartment for rent", location: "Kololo, Kampala", price: 3200000, currency: "UGX / month", bedrooms: 2, bathrooms: 2, area: 120, areaUnit: "sqm", imageUrl: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=85", featured: true, description: "Contemporary furnished apartment close to shops and restaurants.", agentName: "Prime Homes", agentPhone: "+256 772 451 220" },
  { id: "3", title: "Titled plot near the expressway", type: "Land", location: "Kira, Wakiso", price: 95000000, currency: "UGX", bedrooms: 0, bathrooms: 0, area: 25, areaUnit: "decimals", imageUrl: "https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=85", featured: false, description: "Flat residential land with a ready title and road access.", agentName: "David Okello", agentPhone: "+256 758 440 830" }
];
const heroSlides = [
  { image: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=2000&q=90", title: "Find a place that", emphasis: "feels like home.", location: "Beautiful homes across Uganda" },
  { image: fallback[1].imageUrl.replace("w=1200", "w=2000"), title: "Make room for", emphasis: "everyday living.", location: "Apartments in Kampala and beyond" },
  { image: fallback[0].imageUrl.replace("w=1200", "w=2000"), title: "Find your next", emphasis: "place in the sun.", location: "Homes, land and new beginnings" },
];

export default function Home() {
  const [properties, setProperties] = useState<Property[]>(fallback);
  const [heroIndex, setHeroIndex] = useState(0);
  const [plans, setPlans] = useState<Plan[]>([]);
  const [type, setType] = useState(""); const [location, setLocation] = useState(""); const [bedrooms, setBedrooms] = useState(""); const [sort, setSort] = useState("");
  const [selected, setSelected] = useState<Property | null>(null); const [saved, setSaved] = useState<string[]>([]); const [notice, setNotice] = useState(""); const [listingOpen, setListingOpen] = useState(false); const [token, setToken] = useState(""); const [accountOpen, setAccountOpen] = useState(false); const [registering, setRegistering] = useState(false); const [accountMethod, setAccountMethod] = useState<"email"|"phone">("email");
  const displayPlans = plans.length ? plans : [{ id: "starter", name: "Starter", price: 25000, listings: 1, featured: false }, { id: "professional", name: "Professional", price: 75000, listings: 5, featured: true }];

  useEffect(() => { const stored = localStorage.getItem("nikspeed-saved"); const authToken = localStorage.getItem("nikspeed-token"); if (stored) { try { setSaved(JSON.parse(stored)); } catch { localStorage.removeItem("nikspeed-saved"); } } if (authToken) setToken(authToken); Promise.all([fetch(`${api}/api/properties`), fetch(`${api}/api/plans`)]).then(async ([propertyResponse, planResponse]) => { if (propertyResponse.ok) setProperties(await propertyResponse.json()); if (planResponse.ok) setPlans(await planResponse.json()); }).catch(() => undefined); }, []);
  useEffect(() => { const timer = window.setInterval(() => setHeroIndex(index => (index + 1) % heroSlides.length), 6000); return () => window.clearInterval(timer); }, []);
  async function search(event?: FormEvent) { event?.preventDefault(); const params = new URLSearchParams(); if (type) params.set("type", type); if (location) params.set("location", location); if (bedrooms) params.set("bedrooms", bedrooms); if (sort) params.set("sort", sort); try { const response = await fetch(`${api}/api/properties?${params}`); if (response.ok) setProperties(await response.json()); else setNotice("Listings could not be loaded. Please try again."); } catch { setNotice("The marketplace API is unavailable. Please try again shortly."); } }
  function toggleSave(id: string) { const next = saved.includes(id) ? saved.filter((value) => value !== id) : [...saved, id]; setSaved(next); localStorage.setItem("nikspeed-saved", JSON.stringify(next)); window.dispatchEvent(new Event("nikspeed-saved-change")); }
  async function enquire(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; const form = new FormData(event.currentTarget); try { const response = await fetch(`${api}/api/enquiries`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ propertyId: selected.id, name: form.get("name"), email: form.get("email"), phone: form.get("phone"), message: form.get("message") }) }); const data = await response.json().catch(() => null); setNotice(response.ok ? "Your enquiry is on its way to the advertiser." : data?.message || "Please complete your name and email."); if (response.ok) setSelected(null); } catch { setNotice("Your enquiry could not be sent. Please try again shortly."); } }
  function openListing() { if (token) setListingOpen(true); else { setRegistering(false); setAccountOpen(true); } }
  function openAccount(createAccount: boolean) { setRegistering(createAccount); setAccountMethod("email"); setAccountOpen(true); }
  async function startListing(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const planId = String(form.get("planId")); try { const response = await fetch(`${api}/api/payments/checkout`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ planId, advertiserName: form.get("name"), email: form.get("email") }) }); const data = await response.json().catch(() => null); if (!response.ok) { setNotice(data?.detail || data?.message || "Could not start checkout."); return; } if (data?.checkout?.paymentLink) { window.location.assign(data.checkout.paymentLink); return; } setNotice(data?.checkout?.status === "configuration_required" ? "Payments are not configured yet. Please contact our team to purchase listing credits." : "The payment link could not be created. Please try again shortly."); } catch { setNotice("The payment service is unavailable. Please try again shortly."); } }
  async function authenticate(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const endpoint = registering ? "register" : "login"; const identifier = form.get(accountMethod === "phone" ? "phone" : "email"); try { const response = await fetch(`${api}/api/auth/${endpoint}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: registering ? form.get("name") : undefined, email: accountMethod === "email" ? identifier : undefined, phone: accountMethod === "phone" ? identifier : undefined, password: form.get("password") }) }); const data = await response.json().catch(() => null); if (!response.ok) { setNotice(data?.message || "Could not sign in. Check your details."); return; } localStorage.setItem("nikspeed-token", data.token); localStorage.setItem("nikspeed-name", data.name); if (data.email) localStorage.setItem("nikspeed-email", data.email); setToken(data.token); setAccountOpen(false); window.location.assign("/dashboard"); } catch { setNotice("The account service is unavailable. Please try again shortly."); } }

  return <SiteShell onSignIn={()=>openAccount(false)} onRegister={()=>openAccount(true)}><main>
    <section className="hero" id="top" aria-roledescription="carousel" aria-label="Featured Ugandan properties"><div className="hero-backgrounds" aria-hidden="true">{heroSlides.map((slide,index)=><div key={slide.image} className={`hero-slide${heroIndex===index?" is-active":""}`} style={{backgroundImage:`url("${slide.image}")`}} />)}</div><div className="hero-content"><p className="eyebrow">UGANDA&apos;S PROPERTY MARKETPLACE</p><h1 aria-live="polite">{heroSlides[heroIndex].title}<br /><em>{heroSlides[heroIndex].emphasis}</em></h1><p className="hero-copy">{heroSlides[heroIndex].location}. Explore homes for sale, apartments for rent and land across Uganda.</p><div className="carousel-controls" aria-label="Featured property slides"><button type="button" className="carousel-arrow" aria-label="Previous featured property" onClick={()=>setHeroIndex(index=>(index+heroSlides.length-1)%heroSlides.length)}>←</button>{heroSlides.map((slide,index)=><button type="button" key={slide.image} className={`carousel-dot${heroIndex===index?" is-active":""}`} aria-label={`Show slide ${index+1}: ${slide.location}`} aria-current={heroIndex===index?"true":undefined} onClick={()=>setHeroIndex(index)} />)}<button type="button" className="carousel-arrow" aria-label="Next featured property" onClick={()=>setHeroIndex(index=>(index+1)%heroSlides.length)}>→</button></div></div><form className="search" onSubmit={(event) => search(event)}><select value={type} onChange={(event) => setType(event.target.value)}><option value="">All property types</option><option>House for sale</option><option>Apartment for rent</option><option>Land</option></select><input value={location} onChange={(event) => setLocation(event.target.value)} placeholder="Location e.g. Kololo" /><button>Search properties →</button></form></section>
    <section className="stats"><div><strong>{properties.length}</strong><span>active listings</span></div><div><strong>Uganda</strong><span>homes, rentals and land</span></div><div><strong>Local</strong><span>advertisers</span></div></section>
    <section className="listings" id="browse"><div className="section-head"><div><p className="eyebrow">CURATED FOR YOU</p><h2>Homes worth seeing</h2></div><Link href="/saved">{saved.length} saved · View shortlist →</Link></div><div className="filters"><select value={bedrooms} onChange={(event) => setBedrooms(event.target.value)}><option value="">Any bedrooms</option><option value="1">1+ bedrooms</option><option value="2">2+ bedrooms</option><option value="3">3+ bedrooms</option></select><select value={sort} onChange={(event) => { setSort(event.target.value); setTimeout(() => search(), 0); }}><option value="">Featured first</option><option value="price-asc">Price: low to high</option><option value="price-desc">Price: high to low</option></select><button className="quiet" onClick={() => search()}>Apply filters</button></div><div className="grid">{properties.map((property) => <article className="card" key={property.id}><div className="image" style={{ backgroundImage: `url(${property.imageUrl})` }}><Link className="property-image-link" href={`/listings/${property.id}`} aria-label={`View ${property.title}`}/>{property.featured && <span>Featured</span>}<button className="save" aria-label={saved.includes(property.id) ? `Remove ${property.title} from saved homes` : `Save ${property.title}`} aria-pressed={saved.includes(property.id)} onClick={() => toggleSave(property.id)}>{saved.includes(property.id) ? "♥" : "♡"}</button></div><div className="card-body"><p className="type">{property.type}</p><h3>{property.title}</h3><p className="location">⌖ {property.location}</p><LocationLink location={property.location}/><p className="price">{property.currency} {money(property.price)}</p><p className="details">{property.bedrooms ? `${property.bedrooms} beds · ${property.bathrooms} baths · ` : ""}{property.area} {property.areaUnit}</p><button className="link-button" onClick={() => setSelected(property)}>View details →</button></div></article>)}</div></section>
    <section className="advertise" id="advertise"><div><p className="eyebrow">FOR AGENTS & OWNERS</p><h2>Put your property<br />in front of buyers.</h2><p>Choose a listing package, complete payment, and reach thousands of people actively looking for their next property.</p><button onClick={openListing}>Start your listing</button></div><div className="plans">{displayPlans.map((plan) => <div className="plan" key={plan.id}><h3>{plan.name}</h3><strong>UGX {money(plan.price)}</strong><p>{plan.listings} listing{plan.listings > 1 ? "s" : ""} · 30 days{plan.featured ? " · Featured" : ""}</p><button onClick={openListing}>Choose plan</button></div>)}</div></section>
    {notice && <div className="toast">{notice}<button onClick={() => setNotice("")}>×</button></div>}
    {selected && <div className="overlay" role="dialog" aria-modal="true"><div className="modal detail"><button className="close" onClick={() => setSelected(null)}>×</button><div className="detail-image" style={{ backgroundImage: `url(${selected.imageUrl})` }} /><div className="modal-content"><p className="type">{selected.type}</p><h2>{selected.title}</h2><p className="location">⌖ {selected.location}</p><LocationLink location={selected.location}/><h3>{selected.currency} {money(selected.price)}</h3><p>{selected.description}</p><div className="feature-row"><span>{selected.bedrooms || "Land"} {selected.bedrooms ? "beds" : ""}</span><span>{selected.bathrooms || "—"} baths</span><span>{selected.area} {selected.areaUnit}</span></div><form className="enquiry" onSubmit={enquire}><h3>Contact {selected.agentName}</h3><input name="name" placeholder="Your name" required /><input name="email" type="email" placeholder="Email address" required /><input name="phone" placeholder="Phone number" /><textarea name="message" defaultValue={`I am interested in ${selected.title}.`} /><button>Send enquiry</button></form></div></div></div>}
    {listingOpen && <div className="overlay" role="dialog" aria-modal="true"><form className="modal form-modal" onSubmit={startListing}><button type="button" className="close" onClick={() => setListingOpen(false)}>×</button><p className="eyebrow">ADVERTISER ACCOUNT</p><h2>List your property</h2><p>Buy a listing credit first. You&apos;ll add property details after payment confirmation.</p><input name="name" placeholder="Your name or agency" defaultValue={typeof window!=="undefined"?localStorage.getItem("nikspeed-name")||"":""} required /><input name="email" type="email" placeholder="Business email" defaultValue={typeof window!=="undefined"?localStorage.getItem("nikspeed-email")||"":""} required /><select name="planId">{displayPlans.map((plan) => <option key={plan.id} value={plan.id}>{plan.name} — UGX {money(plan.price)}</option>)}</select><button>Continue to payment →</button></form></div>}
    {accountOpen && <div className="overlay" role="dialog" aria-modal="true" aria-labelledby="account-title"><form className="modal form-modal" onSubmit={authenticate}><button type="button" className="close" onClick={() => setAccountOpen(false)} aria-label="Close account dialog">×</button><p className="eyebrow">ADVERTISER ACCOUNT</p><h2 id="account-title">{registering ? "Create your account" : "Welcome back"}</h2><div className="account-methods" role="group" aria-label="Choose account method"><button type="button" className={accountMethod === "email" ? "selected" : ""} onClick={() => { setAccountMethod("email"); setNotice(""); }}>Email</button><button type="button" className={accountMethod === "phone" ? "selected" : ""} onClick={() => { setAccountMethod("phone"); setNotice(""); }}>Phone number</button></div>{accountMethod === "phone" ? <><p className="auth-hint">Use your phone number with country code, for example +256…</p>{registering && <input name="name" placeholder="Your name or agency" required />}<input name="phone" type="tel" autoComplete="tel" placeholder="Phone number (e.g. +256 7…)" required/><input name="password" type="password" placeholder="Password (8+ characters)" minLength={8} required/></> : <>{registering && <input name="name" placeholder="Your name or agency" required />}<input name="email" type="email" autoComplete="email" placeholder="Business email" required/><input name="password" type="password" autoComplete={registering ? "new-password" : "current-password"} placeholder="Password (8+ characters)" minLength={8} required/></>}<button>{registering ? "Create account" : "Sign in"}</button><div className="social-auth"><button type="button" className="social-auth-button" onClick={() => setNotice("Apple sign-in is not connected yet. Provider setup is required.")}>Continue with Apple</button><button type="button" className="social-auth-button" onClick={() => setNotice("LinkedIn sign-in is not connected yet. Provider setup is required.")}>Continue with LinkedIn</button></div>{notice && <p className="auth-hint" role="status">{notice}</p>}<button type="button" className="link-button" onClick={() => { setRegistering(!registering); setNotice(""); }}>{registering ? "Already registered? Sign in" : "New advertiser? Create an account"}</button></form></div>}
  </main></SiteShell>;
}
